version: '3.8'

services:
  # --- SERVICIO DEL BACKEND ---
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  # --- SERVICIO DEL FRONTEND ---
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend